name: iOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.1'
          channel: 'stable'

      - name: Call flutter pub get
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Compress App Bundle
        run: |
          cd build/ios/iphoneos
          zip -r Runner.app.zip Runner.app

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
          files: |
            build/ios/iphoneos/Runner.app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
