name: Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.1'
          channel: 'stable'

      - name: Call flutter pub get
        run: flutter pub get

      - name: Enable Windows Support
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows --release

      - name: Organize Files
        run: |
          mkdir build\windows\dist
          xcopy /E /I build\windows\runner\Release build\windows\dist\
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
          files: |
            build/windows/dist/my_test_app.exe
            build/windows/runner/Release/*.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

